FROM ubuntu:18.04

RUN uname -m

RUN apt-get update

RUN python3 --version

RUN ls

RUN pwd

RUN uname -m
